export enum MainEnums {
  CEP_LENGTH = 8,
  MAIN_PAGE_SIZE = 1,
  MAIN_CURRENT_PAGE = 0,
  FIRST_CONTENT = 0,

  INITIAL_PAGE_SIZE = 10,
  INITIAL_TOTAL_PAGES = 0,

  ACTION_URL_SEGMENT = 0,

  SHOW_TOASTER_TIME = 10,
  CLOSE_TOASTER_TIME = 3000,

  SIDENAV_OPENED_PAGE_SIZE = 1050
}
